### PR TITLE
Added a taskbar to the UI, new polygon functionalities and some bugfixes

### PR DESCRIPTION
**Pull request by lrosemberg**
# Description

Check here the new features and bugfixes (video - 2 min):
https://share.cleanshot.com/3zdWX7rZ

CleanShot 2024-08-16 at 21 01 39@2x

Hello, I created a user interface for the application, and fixed some bugs I found while I was developing.
This PR is an addition  to the changes contained in my previous PR as well (#10)

In this PR the following changes were made:
- Inserted a new taskbar, which allows access to the following functions: Polygon mode, Line mode, Undo, Discard current, Clear all polygons and Save image
- I remade the coordinate menu
- When you click on the start point when drawing a polygon, the polygon is completed, without the need to press enter
- I adjusted the spacing of the sections
- I simplified some logics

In addition, I fixed the following bugs:
- When scrolling to zoom in, the page scrolled together
- In line insertion mode, the logic was wrong and did not draw the second arc at the end point of the line

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by lrosemberg** [comment]
Hello, this PR contains the changes made previously in #10, because I needed some existing codes in the previous PR and would not like to open a single giant PR.

@capjamesg @yeldarby

**Comment by capjamesg** [comment]
Great work! I love the feature where you can click on the origin point on the polygon to complete the polygon.

One note: When I tested this on my Macbook Air at full resolution, I see some overflow out of the main container:

Screenshot 2024-08-19 at 08 46 07

Can you update the styles so that the page stays within the viewport container?

**Review by capjamesg — CHANGES_REQUESTED** [review]
Looks good! See my comment on the overflow of the main container. After that point has been addressed, I can merge this PR.

**Comment by lrosemberg** [comment]
> Looks good! See my comment on the overflow of the main container. After that point has been addressed, I can merge this PR.


Hey @capjamesg, I fixed that and other css minor tweaks, can you check please?

**Review by capjamesg — APPROVED** [review]
The page works well on desktop at different resolutions now. I'm going to merge this PR.

**Comment by capjamesg** [comment]
Thank you for your contribution! The user experience Polygon Zone is significantly better than it was!

**Pull request merged**
